[lint]
select = ["E", "F", "W", "UP", "I"]
ignore = ["E501", "F401"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["F401", "F811"]

[format]
quote-style = "double"
indent-style = "space"
