target-version = "py38"
line-length = 120
select = ["E", "F", "W", "I", "N", "UP"]
ignore = ["E501"]  # line too long - we control with line-length

[per-file-ignores]
"tests/*" = ["F401", "F811"]  # unused imports, redefinition
